BLUETOOTH = 'ic:round-bluetooth'
SERIAL = 'ph:usb-fill'
MANAGE_PROFILES = 'carbon:user-profile'
MANAGE_TEST_CASES = 'fluent-mdl2:test-case'
RUN_SIMULATOR = 'carbon:play-filled'
RIGHT_ARROW = 'basil:arrow-right-solid'
DOWN_ARROW = 'basil:arrow-down-solid'
